# Welcome to Jekyll!

title: UQ student Shuo
description: This blog documents my journey as a student in Australia, focusing on the courses I am studying. Join me as I explore new knowledge and experiences!

github_username: jph00

email: wsncepu@163.com
twitter_username:

use_math: true

# Keeping the default theme
theme: minima

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge 
